# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - farm-profit-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: gigahackhakaton2025shifthappens.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7C470895156F49E3A098D7986DDE9B07 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_937EC737428D41128548A574FA0AC567 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: gigahackhakaton2025shifthappens.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7C470895156F49E3A098D7986DDE9B07 }}/farmprofitapp:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_925B7986F6CB490898DCDF5E8CD26370 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D94780B7344146DFA913DAA1AB292F81 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_00CF823F85F04B4AA0B1BBFD88D202E4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'farm-profit-webapp'
          slot-name: 'Production'
          images: 'gigahackhakaton2025shifthappens.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7C470895156F49E3A098D7986DDE9B07 }}/farmprofitapp:${{ github.sha }}'
          